"""Generate LaTeX table fragments for the §4.7.7 ablation + paired-tests subsection.

Inputs:
  - results/paper_stage6/fusion_cldnn_stft_ablation_3090/rml2016a/<variant>/status.json
  - results/paper_stage6/fusion_cldnn_stft_aug_ls_3090/rml2016a/status.json (full combination)
  - results/paper_stage6/proposed_paired_tests/{paired_bootstrap.csv, mcnemar.csv}

Outputs:
  - docs/paper/course_report/tables/ablation_results.tex
  - docs/paper/course_report/tables/paired_tests_summary.tex
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ABLATION_ROOT = REPO_ROOT / "results/paper_stage6/fusion_cldnn_stft_ablation_3090/rml2016a"
FULL_STATUS = REPO_ROOT / "results/paper_stage6/fusion_cldnn_stft_aug_ls_3090/rml2016a/status.json"
PAIRED_DIR = REPO_ROOT / "results/paper_stage6/proposed_paired_tests"
OUT_DIR = REPO_ROOT / "docs/paper/course_report/tables"


def load_status_runs(status_path: Path) -> list[dict]:
    if not status_path.exists():
        return []
    data = json.loads(status_path.read_text(encoding="utf-8"))
    return [v for v in data.get("runs", {}).values() if isinstance(v, dict) and v.get("status") == "completed"]


def aggregate(runs: list[dict]) -> dict[str, tuple[float, float]]:
    """Compute mean and std of overall/low/mid/high SNR accuracy across seeds."""
    import statistics as st
    keys = ("overall_accuracy", "low_snr_accuracy", "mid_snr_accuracy", "high_snr_accuracy")
    out = {}
    for k in keys:
        vals = [r.get(k) for r in runs if r.get(k) is not None]
        if not vals:
            out[k] = (float("nan"), float("nan"))
        else:
            out[k] = (sum(vals) / len(vals), st.pstdev(vals) if len(vals) > 1 else 0.0)
    return out


def fmt(x: tuple[float, float]) -> str:
    if x[0] != x[0]:  # NaN
        return "--"
    return f"\\(\\mathbf{{{x[0]:.4f}}}\\pm{x[1]:.4f}\\)" if x[1] >= 0 else f"\\({x[0]:.4f}\\)"


def fmt_plain(x: tuple[float, float]) -> str:
    if x[0] != x[0]:
        return "--"
    return f"\\({x[0]:.4f}\\pm{x[1]:.4f}\\)"


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # 1) Ablation results table
    rows: list[tuple[str, dict[str, tuple[float, float]]]] = []
    for variant in ("arch_only", "arch_aug", "arch_ls"):
        runs = load_status_runs(ABLATION_ROOT / variant / "status.json")
        rows.append((variant, aggregate(runs)))
    full_runs = load_status_runs(FULL_STATUS)
    rows.append(("full (arch+aug+LS, 提案)", aggregate(full_runs)))

    lines = [
        "% auto-generated by scripts/paper/generate_section_4_7_7_tables.py",
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\caption{提案模型 \\texttt{fusion\\_cldnn\\_stft} 的单干预消融（三训练种子均值 \\(\\pm\\) 标准差）。变体 \\texttt{arch\\_only} 关闭增强且 \\(\\epsilon=0\\)；\\texttt{arch\\_aug} 仅开增强；\\texttt{arch\\_ls} 仅开标签平滑；``full'' 行复用第~\\ref{sec:results-fusion-cldnn-stft}~节的提案模型结果。所有变体使用相同 RTX 3090 硬件、相同固定划分、相同三训练种子。}",
        "  \\label{tab:proposed-ablation-results}",
        "  \\small",
        "  \\begin{tabularx}{\\textwidth}{Xcccc}",
        "    \\toprule",
        "    变体 & 整体 & 低 SNR & 中 SNR & 高 SNR \\\\",
        "    \\midrule",
    ]
    for label, agg in rows:
        # Escape underscores in label for LaTeX (or wrap in \texttt{})
        if "_" in label and "(" not in label:
            disp = f"\\texttt{{{label.replace('_', chr(0x5C) + '_')}}}"
        else:
            disp = label
        lines.append(
            f"    {disp} & {fmt_plain(agg['overall_accuracy'])} & {fmt_plain(agg['low_snr_accuracy'])} & {fmt_plain(agg['mid_snr_accuracy'])} & {fmt_plain(agg['high_snr_accuracy'])} \\\\"
        )
    lines.extend([
        "    \\bottomrule",
        "  \\end{tabularx}",
        "\\end{table}",
    ])
    (OUT_DIR / "ablation_results.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_DIR / 'ablation_results.tex'}")

    # 2) Paired tests summary
    boot_path = PAIRED_DIR / "paired_bootstrap.csv"
    mcn_path = PAIRED_DIR / "mcnemar.csv"
    if not (boot_path.exists() and mcn_path.exists()):
        print(f"!! paired tests files missing under {PAIRED_DIR}; emitting placeholder")
        (OUT_DIR / "paired_tests_summary.tex").write_text(
            "% paired tests not yet generated; run scripts/paper/run_proposed_paired_tests.py\n",
            encoding="utf-8",
        )
        return 0

    with open(boot_path) as f:
        boot = list(csv.DictReader(f))
    with open(mcn_path) as f:
        mcn = list(csv.DictReader(f))
    mcn_idx = {(r["model_a"], r["model_b"], r["scope"]): r for r in mcn}

    plines = [
        "% auto-generated by scripts/paper/generate_section_4_7_7_tables.py",
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\caption{提案模型相对参照的配对统计检验。差值定义为``\\(\\mathrm{Acc}(\\text{model\\_a})-\\mathrm{Acc}(\\text{model\\_b})\\)''；自助重采样 10000 次，种子 42；McNemar 使用连续性修正卡方近似（\\(\\mathrm{df}=1\\)）。}",
        "  \\label{tab:proposed-paired-tests}",
        "  \\scriptsize",
        "  \\setlength{\\tabcolsep}{4pt}",
        "  \\begin{tabularx}{\\textwidth}{Xlrrrr}",
        "    \\toprule",
        "    比较 & 范围 & 配对数 & 准确率差值 & 95\\% CI 是否跨 0 & McNemar \\(p\\) \\\\",
        "    \\midrule",
    ]
    for r in boot:
        scope_disp = "整体" if r["scope"] == "overall" else "低 SNR"
        crosses = "是" if r["crosses_zero"] in ("True", "true", "yes") else "否"
        delta = float(r["delta_mean"])
        lo = float(r["ci_low"])
        hi = float(r["ci_high"])
        mcn_row = mcn_idx.get((r["model_a"], r["model_b"], r["scope"]))
        p_str = f"{float(mcn_row['mcnemar_p']):.3e}" if mcn_row else "--"
        plines.append(
            f"    {r['model_a']} vs.\\ {r['model_b']} & {scope_disp} & {int(r['n_pairs']):,} & "
            f"\\({delta:+.4f}\\) [\\({lo:+.4f},{hi:+.4f}\\)] & {crosses} & \\({p_str}\\) \\\\"
        )
    plines.extend([
        "    \\bottomrule",
        "  \\end{tabularx}",
        "\\end{table}",
    ])
    (OUT_DIR / "paired_tests_summary.tex").write_text("\n".join(plines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_DIR / 'paired_tests_summary.tex'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
